### ISSUE TITLE
一直在转圈无法查询

### ISSUE THREAD

**Issue by zhucaidan** [GitHubPangHu/whoisQuery#1]
一直在转圈无法查询，PHP7.4 宝塔环境

![image](https://github.com/GitHubPangHu/whoisQuery/assets/47970938/cd450872-07c6-46af-b5bd-51cf63410d4a)

**Comment by GitHubPangHu** [comment]
我这边没有复现您的问题，能否提供一下部署后的域名，我去看一下报错是什么。
或者您在浏览器右键检查，选择网络，然后页面查询，看返回的是什么错误。没有错误，我没办法定位问题。

**Comment by GitHubPangHu** [comment]
参考下面图片样式
![页面](https://github.com/GitHubPangHu/image/raw/main/yemian.png)

**Comment by GitHubPangHu** [comment]
长时间没有回应，我就先把issue关闭了，有问题的话，请重新发issue
